### ISSUE TITLE
Edit profile picture upload for artists who are not musicians.

### ISSUE THREAD

**Issue by samuthojo** [jesstrux/loveartswebsite#25]
For the case when the user is not a musician he is to upload a picture. Now the next time he edits his profile, he will probably upload another picture. Why are we not deleting the previous picture. Shouldn't we!?

**Comment by jesstrux** [comment]
Hey @samuthojo the thing is the artist anatakiwa awe na multiple works so we're thinking of incorporating that in the future ikishakua confirmed but you're right. For right now it makes sense to delete the old one so just go ahead and do that.

**Comment by samuthojo** [comment]
Great @jesstrux
